### ISSUE TITLE
Corrigir comportamento do gráficos de barras, deve apresentar todas as categorias

### ISSUE THREAD

**Issue by murilo-dan** [fga-eps-mds/2021-2-SiGeD-Doc#44]
**Descrição**
No gráfico de barras, não estão sendo apresentadas todas as demandas por categoria. O sistema parece estar limitando para 5 categorias diferentes apenas.

**Objetivo**
O gráfico de barras deve apresentar todas as demandas, independente de quantas categorias existam.

**Tarefas**
- [x] Verificar o que está causando a limitação.
- [ ] Remover a limitação para apresentar todas as categorias.

**Informações adicionais**
A limitação pode estar ocorrendo por uma decisão dos desenvolvedores, ou talvez seja uma limitação automática pela forma que foi implementada o gráfico. Independentemente do motivo, o gráfico deve apresentar todas as categorias vinculadas a uma demanda.

**Checklist**
- [ ] A issue possui nome significativo.
- [ ] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [ ] A issue possui labels.

**Comment by nicaloribeiro** [comment]
Após a separação dos gráficos em páginas, os problemas relacionados a essa issue foram resolvidos. O gráfico de barras está apresentando todas as categorias corretamente
